services:
  kuma:
    image: louislam/uptime-kuma
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"
    expose:
      - 3001
    #ports:
      #- 3001:3001
    environment:
      NODE_EXTRA_CA_CERTS: /app/data/certs/ca.pem
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kuma.entrypoints=websecure"
      - "traefik.http.routers.kuma.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.kuma.tls.certresolver=http-challenge"
    volumes:
      - ./data:/app/data
#      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default
      - traefik-proxy
      - socket-proxy
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    security_opt:
      - "no-new-privileges:true"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - SERVERPORT=51820 #optional
      - PEERDNS=auto #optional
#      - INTERNAL_SUBNET=${NETWORK_SUBNET:-10.13.13.0} #optional
      - ALLOWEDIPS=${ALLOWED_IPS:-0.0.0.0/0} #optional
      - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
    volumes:
      - ./wireshark-config:/config
      - /lib/modules:/lib/modules #optional
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
networks:
  default:
  traefik-proxy:
    name: traefik-proxy
    external: true
  socket-proxy:
    external: true
